# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18676a89ae59a5ffe55cd21b2dd6acefd5e23b0de07d2edf2648f64adb8a7d1c1ecf1ab05e340fcf3b02b9c295c91367acd32988ff67d05c1351227008b0a857

test:
  secret_key_base: b0ef0dcb437c24e4202d1be6b9f65de81c50d1ed167124955adf9fdbdc2936b852dc07fac023a9ef47f4af4a255b360ce270bb32b7dc1be6ae12b8141aa0533e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
